-- ENCRYPTION_WALLET_LOCATION =
--  (SOURCE =(METHOD = FILE)(METHOD_DATA =
--    (DIRECTORY = /u01/app/oracle/admin/$ORACLE_SID/encryption_keystore/)))

ADMINISTER KEY MANAGEMENT
    CREATE KEYSTORE '/u01/app/oracle/admin/cdb1/encryption_keystore/'
    IDENTIFIED BY MYPASSWORD;

ADMINISTER KEY MANAGEMENT
    SET KEYSTORE OPEN IDENTIFIED BY MYPASSWORD CONTAINER = ALL;

ADMINISTER KEY MANAGEMENT
    SET KEYSTORE CLOSE IDENTIFIED BY MYPASSWORD CONTAINER = ALL;

ADMINISTER KEY MANAGEMENT
    SET KEY IDENTIFIED BY MYPASSWORD
        WITH BACKUP
        CONTAINER = ALL;