SELECT *
  FROM V$OPTION
 WHERE PARAMETER = 'Oracle Database Vault';

SHUTDOWN IMMEDIATE
EXIT

$ CD $ORACLE_HOME/RDBMS/LIB
$ MAKE -F INS_RDBMS.MK DV_OFF
$ CD $ORACLE_HOME/BIN
$ RELINK ORACLE

STARTUP
ALTER TRIGGER DVSYS.DV_BEFORE_DDL_TRG
    DISABLE;
ALTER TRIGGER DVSYS.DV_AFTER_DDL_TRG
    DISABLE;

ALTER TRIGGER DVSYS.DV_BEFORE_DDL_TRG
    ENABLE;
ALTER TRIGGER DVSYS.DV_AFTER_DDL_TRG
    ENABLE;

SHUTDOWN IMMEDIATE
EXIT

$ CD $ORACLE_HOME/RDBMS/LIB
$ MAKE -F INS_RDBMS.MK DV_ON
$ CD $ORACLE_HOME/BIN
$ RELINK ORACLE

STARTUP
EXIT

---------------

EXEC DBMS_MACADM.DISABLE_DV;
SHUTDOWN IMMEDIATE
STARTUP

EXEC DBMS_MACADM.ENABLE_DV;

SELECT VALUE
  FROM V$OPTION
 WHERE PARAMETER = 'Oracle Label Security';

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
SHUTDOWN IMMEDIATE
STARTUP