SELECT TO_CHAR (.03, 'FMS999G999G999G990D00') FROM DUAL;

CREATE OR REPLACE FUNCTION ZERO (IN_NUMBER IN NUMBER)
    RETURN VARCHAR2
IS
    OUT_NUMBER   VARCHAR2 (30);
BEGIN
    CASE
        WHEN SUBSTR (IN_NUMBER, 1, 1) = '.'
        THEN
            OUT_NUMBER := '0' || IN_NUMBER;
        WHEN SUBSTR (IN_NUMBER, 1, 2) = '-.'
        THEN
            OUT_NUMBER := '-0.' || SUBSTR (IN_NUMBER, 3);
        ELSE
            OUT_NUMBER := IN_NUMBER;
    END CASE;

    RETURN OUT_NUMBER;
END;