  SELECT SE.SID,
         SE.USERNAME,
         ROUND (PR.PGA_USED_MEM / POWER (1024, 2))         PGA_USED_MB,
         ROUND (PR.PGA_ALLOC_MEM / POWER (1024, 2))        PGA_ALLOC_MB,
         ROUND (PR.PGA_FREEABLE_MEM / POWER (1024, 2))     PGA_FREEABLE_MB,
         ROUND (PR.PGA_MAX_MEM / POWER (1024, 2))          PGA_MAX_MB
    FROM V$SESSION SE, V$PROCESS PR
   WHERE SE.PADDR = PR.ADDR AND SE.TYPE != 'BACKGROUND'
ORDER BY PR.PGA_ALLOC_MEM DESC;

SELECT *
  FROM V$SESSTAT NATURAL JOIN V$STATNAME
 WHERE SID = SYS_CONTEXT ('userenv', 'sid');