SELECT TO_CHAR (ROUND (ALLOCATED / 1024))         ALLOCATED_KB,
       TO_CHAR (ROUND (USED / 1024))              USED_KB,
       TO_CHAR (ROUND (MAX_ALLOCATED / 1024))     MAX_ALL_KB,
       PM.*
  FROM V$SESSION SE, V$PROCESS PR, V$PROCESS_MEMORY PM
 WHERE     SE.SID = SYS_CONTEXT ('userenv', 'sid')
       AND SE.PADDR = PR.ADDR
       AND PR.PID = PM.PID;