SELECT *
  FROM DBA_TAB_STATISTICS
 WHERE OWNER = 'BDSM' AND STALE_STATS = 'YES';

SELECT *
  FROM DBA_IND_STATISTICS
 WHERE OWNER = 'BDSM' AND STALE_STATS = 'YES';

SELECT *
  FROM DBA_TAB_MODIFICATIONS
 WHERE TABLE_OWNER = 'BDSM';

SELECT *
  FROM DBA_AUTOTASK_CLIENT
 WHERE CLIENT_NAME = 'auto optimizer stats collection';
 
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS('BDSM');

BEGIN
    DBMS_STATS.GATHER_TABLE_STATS (OWNNAME   => 'bdsm',
                                   TABNAME   => 'log',
                                   DEGREE    => 2);
END;