/* Formatted on 08/07/2018 16:05:38 (QP5 v5.326) */
CREATE OR REPLACE PROCEDURE DO_SOMETHING (P_TIMES IN NUMBER)
AS
    L_DUMMY   NUMBER;
BEGIN
    FOR I IN 1 .. P_TIMES
    LOOP
        SELECT L_DUMMY + 1 INTO L_DUMMY FROM DUAL;
    END LOOP;
END;


DECLARE
    L_RESULT   BINARY_INTEGER;
BEGIN
    L_RESULT :=
        DBMS_PROFILER.START_PROFILER (
            RUN_COMMENT   => 'do_something: ' || SYSDATE);
    DO_SOMETHING (P_TIMES => 100);
    L_RESULT := DBMS_PROFILER.STOP_PROFILER;
END;

SELECT * FROM PLSQL_PROFILER_RUNS;

  SELECT U.RUNID,
         U.UNIT_NUMBER,
         U.UNIT_TYPE,
         U.UNIT_OWNER,
         U.UNIT_NAME,
         D.LINE#,
         D.TOTAL_OCCUR,
         D.TOTAL_TIME,
         D.MIN_TIME,
         D.MAX_TIME
    FROM PLSQL_PROFILER_UNITS U
         JOIN PLSQL_PROFILER_DATA D
             ON U.RUNID = D.RUNID AND U.UNIT_NUMBER = D.UNIT_NUMBER
   WHERE U.RUNID = 1
ORDER BY U.UNIT_NUMBER, D.LINE#;