DECLARE
    LITERAL   VARCHAR2 (20) := 'BDSM';
BEGIN
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.ENQUOTE_LITERAL (STR => LITERAL));
    DBMS_OUTPUT.PUT_LINE (
        DBMS_ASSERT.ENQUOTE_NAME (STR => LITERAL, CAPITALIZE => FALSE) -- TRUE by default
                                                                      );
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.NOOP (STR => LITERAL));
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.QUALIFIED_SQL_NAME (STR => LITERAL));
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.SIMPLE_SQL_NAME (STR => LITERAL));
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.SCHEMA_NAME (STR => LITERAL));
    DBMS_OUTPUT.PUT_LINE (DBMS_ASSERT.SQL_OBJECT_NAME (STR => LITERAL));
END;