DECLARE
    CLIENT_INFO   VARCHAR2 (100);
    MODULE_NAME   VARCHAR2 (100);
    ACTION_NAME   VARCHAR2 (100);
BEGIN
    DBMS_APPLICATION_INFO.SET_CLIENT_INFO (
        CLIENT_INFO   => 'Hasan - Client info!');
    DBMS_APPLICATION_INFO.READ_CLIENT_INFO (CLIENT_INFO);
    DBMS_OUTPUT.PUT_LINE (CLIENT_INFO);
    DBMS_APPLICATION_INFO.SET_MODULE (MODULE_NAME   => 'This procedure!',
                                      ACTION_NAME   => 'Doing some stuff!');

    DBMS_APPLICATION_INFO.READ_MODULE (MODULE_NAME, ACTION_NAME);
    DBMS_OUTPUT.PUT_LINE (MODULE_NAME || ' +++ ' || ACTION_NAME);

    DBMS_APPLICATION_INFO.SET_ACTION (
        ACTION_NAME   => 'Doing some other stuff!');
    DBMS_APPLICATION_INFO.READ_MODULE (MODULE_NAME, ACTION_NAME);
    DBMS_OUTPUT.PUT_LINE (MODULE_NAME || ' +++ ' || ACTION_NAME);
END;