DECLARE
    PIPENAME   CONSTANT VARCHAR2 (12) := 'signaler';
    RESULT              INTEGER;
    PIPEBUFER           NUMBER := 1;
BEGIN
    RESULT := DBMS_PIPE.CREATE_PIPE (PIPENAME);

    LOOP
        INSERT INTO PIPEBUF
             VALUES (PIPEBUFER, SYSDATE);

        COMMIT;
        DBMS_LOCK.SLEEP (2);

        IF DBMS_PIPE.RECEIVE_MESSAGE (PIPENAME, 0) = 0
        THEN
            DBMS_PIPE.UNPACK_MESSAGE (PIPEBUFER);
            EXIT WHEN PIPEBUFER = 666;
        END IF;
    END LOOP;
END;

DECLARE
    PIPENAME   VARCHAR2 (12) := 'signaler';
    RESULT     INTEGER := DBMS_PIPE.CREATE_PIPE (PIPENAME);
BEGIN
    DBMS_PIPE.PACK_MESSAGE (666);
    RESULT := DBMS_PIPE.SEND_MESSAGE (PIPENAME);
END;