DECLARE
    TYPE A IS TABLE OF NUMBER;

    B   A;
BEGIN
    RUNSTATS_PKG.RS_START;

        SELECT LEVEL
          BULK COLLECT INTO B
          FROM DUAL
    CONNECT BY ROWNUM < 1000000;

    RUNSTATS_PKG.RS_MIDDLE;

        SELECT LEVEL
          BULK COLLECT INTO B
          FROM DUAL
    CONNECT BY ROWNUM < 1000;

    RUNSTATS_PKG.RS_STOP;
END;