BEGIN
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'DB_NAME'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'SESSION_USER'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'SESSIONID'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'SID')); -- v$session
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'LANGUAGE'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'IP_ADDRESS'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'CLIENT_IDENTIFIER'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'HOST'));
    DBMS_OUTPUT.PUT_LINE (SYS_CONTEXT ('USERENV', 'OS_USER'));
END;